version: "3.4"

services:
  server:
    image: ghcr.io/deephaven-examples/deephaven-ib-dhserver:${DH_IB_VERSION:?DH_IB_VERSION not set}
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - api-cache:/cache
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python

  web:
    image: ghcr.io/deephaven/web:${DH_VERSION?DH_VERSION not set}
    expose:
      - '80'
    volumes:
      - ./data:/data
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${DH_VERSION?DH_VERSION not set}
    environment:
      - BACKEND_ADDR=server:8080
    depends_on:
      - server
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:${DH_VERSION?DH_VERSION not set}
    depends_on:
      - web
      - grpc-proxy
      - server
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"

volumes:
    web-tmp:
    api-cache:

