version: "3.4"

services:
  grpc-api:
    build:
      context: .
      args:
        VERSION: ${VERSION:-latest}
        DH_IB_VERSION: ${DH_IB_BRANCH:-main}
        DH_IB_BRANCH: ${DH_IB_BRANCH:-main}
        CACHEBUST: ${CACHEBUST:-0}
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - api-cache:/cache
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python
       #-Ddeephaven.application.dir=/app.d

  web:
    image: ghcr.io/deephaven/web:${VERSION:-latest}
    expose:
      - '80'
    volumes:
      - ./data:/data
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
    environment:
      - BACKEND_ADDR=grpc-api:8080
    depends_on:
      - grpc-api
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:${VERSION:-latest}
    depends_on:
      - web
      - grpc-proxy
      - grpc-api
    ports:
      - "${PORT:-10000}:10000"

volumes:
    web-tmp:
    api-cache:
