#
# A docker image from released python packages
#

FROM ubuntu:22.04

RUN apt update && \
    apt install -y openjdk-11-jdk python3-pip

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/

RUN pip3 install deephaven-ib

CMD python