version: "3.4"

services:
  server:
    image: ghcr.io/deephaven-examples/deephaven-ib:${DH_IB_VERSION:?DH_IB_VERSION not set}
    command: python3 -i -c "from deephaven_server import Server; _server = Server(port=10000, jvm_args=['-Xmx4g']); _server.start()"
    stdin_open: true
    tty: true
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
    volumes:
      - ./data:/data
      - ~/.deephaven:/storage

