
# This is a Docker Compose file for building Interactive Brokers python wheels.
# Ideally, the wheels would be published by IB for installation via pip, but
# (1) IB does not make them available via pypi, and
# (2) the wheels are not redistributable.
# This script lets you build the wheels locally, and then install them via pip.
#
# To build the wheels, run `docker-compose up` from the directory containing this file.
# To install the wheels, run `pip install ./dist/*.whl`.
# After running the script, the wheels will be available in the `./dist` directory.
# The `./build` directory contains the scratch work for building the wheels.
#
# The build process is defined in the `build_ibpy.sh` script.
#
# By using Docker, you can build the wheels in a clean environment that is isolated from your local machine.
# It also will work on any platform that supports Docker.

version: '3.8'

services:
  build:
    image: python:3.10
    environment:
      - IB_VERSION
    volumes:
      - .:/app
      - ./build:/build
      - ./dist:/dist
    command: /bin/bash -c "/app/build_ibpy.sh"