ARG DH_VERSION

FROM ghcr.io/deephaven/server:${DH_VERSION}

RUN apt update && \
    apt install -y python3-pip python3-venv curl zip && \
    pip3 install --upgrade pip setuptools wheel

COPY ./wheels /wheels
COPY ./ib-wheels /ib-wheels

RUN pip3 install /ib-wheels/*.whl && \
    pip3 install /wheels/*.whl && \
    rm -rf /ib-wheels/ /wheels/
