# Delete Docker images after PR merge
#

name: 'Clean up Docker images from PR'

on:
  pull_request:
    types: [closed]

jobs:
  purge-image:
    name: Delete images from ghcr.io
    runs-on: ubuntu-20.04
    steps:
      - name: Delete image (pip-installed Deephaven)
        uses: chipkent/action-cleanup-package@v1.0.3
        with:
          package-name: ${{ github.event.repository.name }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.DEEPHAVEN_INTERNAL_PACKAGE_PAT }}
          github-org: deephaven-examples
      - name: Delete image (Deephaven server image)
        uses: chipkent/action-cleanup-package@v1.0.3
        with:
          package-name: ${{ github.event.repository.name }}-dhserver
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.DEEPHAVEN_INTERNAL_PACKAGE_PAT }}
          github-org: deephaven-examples