
FROM ubuntu:22.04

RUN apt update && \
    apt install -y openjdk-11-jdk python3-pip python3-venv curl zip && \
    pip3 install --upgrade pip setuptools wheel

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/

COPY ./wheels /wheels
COPY ./ib-wheels /ib-wheels

RUN pip3 install /ib-wheels/*.whl && \
    pip3 install /wheels/*.whl && \
    rm -rf /ib-wheels/ /wheels/

CMD python3